apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazel
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hazel
  template:
    metadata:
      labels:
        app: hazel
    spec:
      containers:
      - image: hazelcast/hazelcast:latest
        name: hazel
        ports:
        - containerPort: 80
---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: nginx-deployment
#spec:
#  selector:
#    matchLabels:
#      app: nginx
#  replicas: 2
#  template:
#    metadata:
#      labels:
#        app: nginx
#    spec:
#      containers:
#      - name: nginx
#        image: nginx:1.14.2
#        ports:
#        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-hazelcast-management-center
spec:
  selector:
    matchLabels:
      app: pod-hazelcast-management-center
  template:
    metadata:
      labels:
        app: pod-hazelcast-management-center
    spec:
      containers:
        - image: hazelcast/management-center:latest
          # Always from local, never from Dockerhub
          imagePullPolicy: Always
          # Url to check every 10 seconds if the container is ok
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 8081
          name: container-hazelcast-management-center
#          # Url to check the container is up
#          readinessProbe:
#            httpGet:
#              path: /health
#              port: 8081
#            initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: service-hazelcast-management-center
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: pod-hazelcast-management-center
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: service-hazelcast-server
spec:
  # Headless service, only cluster members
  clusterIP: None
  selector:
    app: pod-hazelcast-server
  ports:
  - protocol: TCP
    port: 5701
    targetPort: 5701
